### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by ghost** [KitCarson88/ionic-augmented-reality#3]
Hi, I cannot install libraries with 'npm install' due to the following error:

npm ERR! While resolving: AugmentedReality@1.0.0
npm ERR! Found: @angular/core@10.2.4
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^10.1.3" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^7.0.0" from @angular-redux/store@10.0.0
npm ERR! node_modules/@angular-redux/store
npm ERR!   @angular-redux/store@"^10.0.0" from the root project

How can I fix it?
Thanks a lot

**Comment by kitcarson88** [comment]
Hi. Probably some dependencies are too old. I have the same error too using the latest versions of node and npm.
Trying a "npm install" with an older version (node v.14.16 and npm v6.14.11) dependencies should install properly. You can try to manage the version of node/npm with nvm software.

**Comment by ghost** [comment]
Thanks, it worked!
